version: '3'

services:
  celery:
    working_dir: /app
    build:
      context: .
      dockerfile: workers/Dockerfile
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  storage1:
    build: .
    ports:
      - "2000:22"
  storage2:
    build: .
    ports:
      - "2001:22"