FROM python:3.6

ADD requirements.txt /app/requirements.txt
ADD ./celery_package/ /app/
WORKDIR /app/

RUN pip install -r requirements.txt

ENTRYPOINT celery worker -A celery_package:celery --concurrency=5 --loglevel=info